sudo: false
language: java
script: mvn clean verify
jdk:
  - openjdk8
after_success:
  - if [ $SONATYPE_USERNAME ] && [ -z $TRAVIS_TAG ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      mvn clean deploy --settings .travis/settings.xml;
      echo "Finished mvn clean deploy for $TRAVIS_BRANCH";
    fi;
  - mvn deploy --settings .travis/settings-abacus.xml -DaltDeploymentRepository=open-nexus-snapshots::default::https://open-nexus.abacus.ch/repository/maven-snapshots/
branches:
  only:
  - master
  - master-abacus
