language: java
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

install: true #skip the install step using true (success)

script:
  - mvn --settings .travis/settings-abacus.xml clean verify

after_success:
  - mvn --settings .travis/settings-abacus.xml deploy -DaltDeploymentRepository=open-nexus-snapshots::default::https://open-nexus.abacus.ch/repository/maven-snapshots/
